basket/urls.py
from django.urls import path




app_name = 'basket'


urlpatterns = [


    
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('basket/', include('basket.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from .views import all_products, category_list, product_detail

app_name = 'store'

urlpatterns = [
    path('', all_products, name = 'all-products'),
    path('<slug:slug>', product_detail, name = 'detail'),
    path('category/<slug:category_slug>', category_list, name = 'category'),
    
    



]

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

# Create your models here.


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active = True)





class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)



    class Meta:
        verbose_name_plural = 'categories'
    

    def __str__(self):
        return self.name


    
    def get_absolute_url(self):
        return reverse('store:category', kwargs={'category_slug': self.slug})




class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.TextField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to = 'images/', default = 'images/default.webp')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager() #default ok
    products = ProductManager()



    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('store:detail', kwargs={'slug':self.slug})


    

basket/views.py
from django.shortcuts import render

# Create your views here.

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product

# Create your views here.


def all_products(request):
    products = Product.products.all()

    context = {
        'products': products
    }
    return render(request, 'store/home.html', context) 







def product_detail(request, slug):
    # product = Product.objects.get(slug = slug)
    product = get_object_or_404(Product, slug = slug, in_stock = True)
    context = {
        'product': product
    }
    
    return render(request, 'store/product_detail.html', context)




def category_list(request, category_slug):
    category = get_object_or_404(Category, slug = category_slug)
    products = Product.objects.filter(category=category)

    context = {
        'products': products
    }
    return render(request, 'store/category.html', context)

store/templates/store/category.html
{% extends 'base.html' %}




{% block content %}



<div class="mt-2 row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
    {% for product in products %}
    <div class="col">
    <div class="card shadow-sm">
        <img src="{{ product.image.url }}"  alt="{{ product.title }}">
        <div class="card-body">
        <p class="card-text">{{ product.title }}</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
            <a href="{{ product.get_absolute_url }}" class="btn btn-sm btn-outline-secondary">View</a>
            </div>
        </div>
        </div>
    </div>
    </div>
        {% empty %}
        <h3>No Book Sorry!</h3>
    {% endfor %}
</div>


{% endblock %}

store/templates/store/home.html
{% extends 'base.html' %}


{% block title %}BookStore{% endblock %}

{% block content %}



    <main class="px-3 mt-4 text-center">
        <h1>Search,Read,Buy,Review</h1>
        <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
        <p class="lead">
        <a href="#" class="btn btn-lg btn-secondary fw-bold border-white bg-dark">Learn more</a>
        </p>
    </main>

    <h3 class="text-center my-4 all-books">All Books</h3>
    <div class="mt-2 row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products %}
        <div class="col">
        <div class="card shadow-sm">
            <img src="{{ product.image.url }}"  alt="{{ product.title }}">
            <div class="card-body">
            <p class="card-text">{{ product.title }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                <a href="{{ product.get_absolute_url }}" class="btn btn-sm btn-outline-secondary">View</a>
                </div>
                <!-- <small class="text-muted">9 mins</small> -->
            </div>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>


    <div class="give_me_margin"></div>

{% endblock %}

store/templates/store/product_detail.html
{% extends 'base.html' %}

{% block title %}{{ product.title }}{% endblock %}

{% block content %}


    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img src="{{ product.image.url }}" class="img-fluid mx-auto d-block" alt="{{ product.title }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h3 text-center">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author}}</span> (Author)</p>
                <p>{{ product.description|slice:":300"}}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">HardBack</div>
                            <div class="col-6 text-end">
                                <span class="h4 fw-bold">
                                    ${{ product.price }}
                                </span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row p-3">
                                <div class="col-6">
                                    <label for="select">Quantity</label>
                                    <select  id="select">
                                        <option value="">1</option>
                                        <option value="">2</option>
                                        <option value="">3</option>
                                        <option value="">4</option>
                                    </select>
                                </div>
                                <div class="col-6 text-end">
                                    <button class="btn btn-outline-secondary" type="button">Add to basket</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>


    <div class="give_me_margin"></div>

{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}My Shop{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- jquery cdn -->
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <!-- jquery cdn -->

    <link rel="stylesheet" href="{% static 'css/main.css'%}">
  </head>
  <body>
    
    <!-- header section -->
    {% include 'header.html' %}
    <!-- / header section -->

    <div class="container font-monospace">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg bg-success">
    <div class="container">
      <a class="navbar-brand text-white" href="{% url 'store:all-products' %}">📔 BookStore</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Library
            </a>
            <ul class="dropdown-menu">
                {% for c in categories %}
                    <li><a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
                {% endfor %}
            </ul>
          </li>
        </ul>
       <!-- ss -->
      </div>
    </div>
  </nav>